services:
  app:
    env_file:
      - .env
    build: .
#      context: .
#      dockerfile: Dockerfile
    ports:
      - "80:8000"
    depends_on:
      db:
        condition: service_healthy
#    command: ["python", "app.py"]

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGUSER: ${DB_USERNAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata: